# Generated by Django 2.1.5 on 2020-05-29 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_refund'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Shipped',
            new_name='shipped',
        ),
        migrations.AddField(
            model_name='order',
            name='returned',
            field=models.BooleanField(default=False),
        ),
    ]
