# Generated by Django 2.1.5 on 2020-05-07 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20200506_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default='1.jpeg', upload_to=''),
            preserve_default=False,
        ),
    ]
