# Generated by Django 2.1.5 on 2020-05-07 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20200507_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='label_name',
            field=models.CharField(blank=True, choices=[('N', 'New'), ('S', 'SALE'), ('D', 'DISCOUNT'), ('O', 'OFFER')], max_length=1, null=True),
        ),
    ]
