# Generated by Django 2.1.5 on 2020-05-08 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_auto_20200508_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_label',
        ),
        migrations.DeleteModel(
            name='ItemCategory',
        ),
    ]
