# Generated by Django 2.1.5 on 2020-05-08 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_auto_20200508_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='listed_on_frontpage',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
