# Generated by Django 2.1.5 on 2020-05-08 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_item_listed_on_frontpage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='listed_on_frontpage',
            new_name='list_on_frontpage',
        ),
    ]
