# Generated by Django 2.1.5 on 2020-05-09 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_order_billing_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bilingaddress',
            old_name='countries',
            new_name='country',
        ),
    ]
