# Generated by Django 2.1.5 on 2020-05-18 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_auto_20200515_2015'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckZipcode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zipcode', models.CharField(max_length=10)),
            ],
        ),
    ]
