# Generated by Django 2.1.5 on 2020-05-19 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0033_wishlisteditem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wishlisted', models.BooleanField(default=False)),
                ('wishlisted_date', models.DateTimeField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='wishlisteditem',
            name='added_date',
        ),
        migrations.AddField(
            model_name='wishlisteditem',
            name='wishlisted',
            field=models.BooleanField(default=False),
        ),
    ]
