# Generated by Django 2.1.5 on 2020-05-19 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_auto_20200519_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlish',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Item'),
        ),
        migrations.AlterField(
            model_name='wishlisteditem',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Item'),
        ),
    ]
