# Generated by Django 2.1.5 on 2020-05-19 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0035_auto_20200519_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlisteditem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
