# Generated by Django 2.1.5 on 2020-05-19 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0036_wishlisteditem_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlish',
            name='item',
        ),
        migrations.AddField(
            model_name='wishlish',
            name='item',
            field=models.ManyToManyField(to='myapp.OrderItem'),
        ),
    ]
