# Generated by Django 2.1.5 on 2020-05-19 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0037_auto_20200519_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlisteditem',
            name='quantity',
        ),
    ]
