# Generated by Django 2.1.5 on 2020-05-19 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0038_remove_wishlisteditem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlish',
            name='item',
            field=models.ManyToManyField(to='myapp.WishlistedItem'),
        ),
    ]
