# Generated by Django 2.1.5 on 2020-05-20 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0039_auto_20200519_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='bilingaddress',
            name='default_address',
            field=models.BooleanField(default=False),
        ),
    ]
