# Generated by Django 2.1.5 on 2020-05-21 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0042_order_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcode',
            name='amount',
            field=models.FloatField(default=10),
            preserve_default=False,
        ),
    ]
